services:
  db:
    image: postgres:14.2-alpine
    env_file:
      - .env
    volumes:
      # - ./backend/postgres/init/create_extension.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nest:
    build: ./backend
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  next:
    build: ./client
    command: npm run dev
    working_dir: /app
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - nest
    
volumes:
  postgres_data: